# Generated by Django 6.0.1 on 2026-01-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recomender', '0003_alter_crophistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='crophistory',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
